apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-ai-api
spec:
  selector:
    matchLabels:
      app: support-ai-api
  template:
    metadata:
      labels:
        app: support-ai-api
    spec:
      containers:
        - name: support-ai-api-container
          image: {{ .Values.container.image }}
          {{- if or .Values.container.api.proxy .Values.container.api.no_proxy }}
          env:
            {{- if .Values.container.api.proxy }}
            - name: HTTP_PROXY
              value: {{ .Values.container.api.proxy }}
            - name: http_proxy
              value: {{ .Values.container.api.proxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.container.api.proxy }}
            - name: https_proxy
              value: {{ .Values.container.api.proxy }}
            {{- end }}
            {{- if .Values.container.api.no_proxy }}
            - name: NO_PROXY
              value: {{ .Values.container.api.no_proxy }}
            - name: no_proxy
              value: {{ .Values.container.api.no_proxy }}
            {{- end }}
          {{- end }}
          command: ["api-server"]
          args: ["--config", "/support-ai-config/config.yaml"]
          ports:
            - containerPort: {{ .Values.container.api.port }}
          volumeMounts:
            - name: config-vol
              mountPath: /support-ai-config
      volumes:
        - name: config-vol
          configMap:
            name: support-ai-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-ai-webapp
spec:
  selector:
    matchLabels:
      app: support-ai-webapp
  template:
    metadata:
      labels:
        app: support-ai-webapp
    spec:
      containers:
        - name: support-ai-webapp-container
          image: {{ .Values.container.image }}
          env:
            - name: API_SVC_URL
              value: http://support-ai-api:{{ .Values.service.api.port }}/api/
          command: ["streamlit", "run", "/app/src/support_ai/webapp.py"]
          args: ["--server.port", "{{ .Values.container.webapp.port }}", "--server.baseUrlPath", "/webapp"]
          ports:
            - containerPort: {{ .Values.container.webapp.port }}
