apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-ai
spec:
  selector:
    matchLabels:
      app: support-ai
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: support-ai
    spec:
      containers:
        - name: support-ai-container
          image: {{ .Values.container.image }}
          {{- if .Values.container.proxy }}
          env:
          - name: HTTP_PROXY
            value: {{ .Values.container.proxy }}
          - name: http_proxy
            value: {{ .Values.container.proxy }}
          - name: HTTPS_PROXY
            value: {{ .Values.container.proxy }}
          - name: https_proxy
            value: {{ .Values.container.proxy }}
          - name: NO_PROXY
            value: 127.0.0.1
          - name: no_proxy
            value: 127.0.0.1
          {{- end }}
          command: ["{{ .Values.container.command }}"]
          args: ["--config", "/support-ai-config/config.yaml"]
          {{- if .Values.container.port }}
          ports:
            - containerPort: {{ .Values.container.port }}
          {{- end }}
          volumeMounts:
            - name: config-vol
              mountPath: /support-ai-config
      volumes:
        - name: config-vol
          configMap:
            name: support-ai-config
