apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-ai
spec:
  ingressClassName: nginx-ingress-controller
  rules:
    - host: support-ai.stage.support-eng.internal
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: support-ai-api
                port:
                  number: {{ .Values.service.api.port }}
          - path: /webapp
            pathType: Prefix
            backend:
              service:
                name: support-ai-webapp
                port:
                  number: {{ .Values.service.webapp.port }}
