apiVersion: v1
kind: Service
metadata:
  name: support-ai-api
spec:
  type: ClusterIP
  selector:
    app: support-ai-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.container.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: support-ai-webapp
spec:
  type: ClusterIP
  selector:
    app: support-ai-webapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.webapp.port }}
      targetPort: {{ .Values.container.webapp.port }}
