apiVersion: v1
kind: Service
metadata:
  name: support-ai
spec:
  type: {{ .Values.service.type }}
  selector:
    app: support-ai
  {{- if .Values.service.port }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  {{- end }}
