apiVersion: v1
kind: Service
metadata:
  name: support-ai
spec:
  type: ClusterIP
  selector:
    app: support-ai
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
