#!/usr/bin/env venv/bin/python

import uuid
import yaml
from lib.const import CONFIG_PATH
from lib.chain import Chain


if __name__ == '__main__':
    with open(CONFIG_PATH, 'r', encoding='utf8') as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
    chain = Chain(config)
    session = str(uuid.uuid4())

    while True:
        query = input(">")
        # transfer query to lower case
        query = query.lower().strip()
        if query in ['exit', 'quit', 'q', 'e', 'x']:
            break
        if not query:
            continue
        for token in chain.ask(query, session=session):
            print(token, end='')
