#!/usr/bin/env python

import yaml
from lib.const import CONFIG_PATH
from lib.datasources.utils import get_datasources
from lib.qa_chain import QAChain


if __name__ == '__main__':
    with open(CONFIG_PATH, 'r', encoding='utf8') as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
    qa_chain = QAChain(config, get_datasources(config))

    while True:
        query = input(">")
        # transfer query to lower case
        query = query.lower().strip()
        if query in ['exit', 'quit', 'q', 'e', 'x']:
            break
        if not query:
            continue
        qa_chain.ask(query)
