#!/usr/bin/env python

import sys
import yaml
from lib.bot import Bot

CONFIG_PATH = "config.yaml"

with open(CONFIG_PATH, 'r') as f:
    data = yaml.load(f, Loader=yaml.FullLoader)

if 'data_dir' not in data or 'model_path' not in data:
    sys.exit("Unexpected config format [{}]".format(data))

Bot(data['data_dir'], data['model_path']).run()
