# [llm]
#   type: llamacpp/openai/huggingface_pipeline
#   model
#   {openai}
#     api_key

basic_model:
  llm:
    type: huggingface_pipeline
    model: databricks/dolly-v2-12b
memory:
  db_connection: "mongodb://XXX"
datasources:
  - type: salesforce
    authentication:
      username: ""
      password: ""
      token: ""
    llm:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
    embeddings:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
  - type: knowledgebase
    authentication:
      username: ""
      password: ""
      token: ""
    llm:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
    embeddings:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
