# [llm]
# type: llamacpp/openai/huggingface_pipeline
# model
# qa_chain_type: stuff/map_reduce/map_rerank/refine
# {openai}
#   api_key

datasources:
  - type: salesforce
    authentication:
      username: ""
      password: ""
      token: ""
    llm:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
    embeddings:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
  - type: knowledgebase
    authentication:
      username: ""
      password: ""
      token: ""
    llm:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
    embeddings:
      type: huggingface_pipeline
      model: databricks/dolly-v2-12b
qa_chain_type: stuff
