#!/usr/bin/env venv/bin/python

import signal
import sys
import time
import yaml
from lib.const import CONFIG_PATH
from lib.datasources.ds_updater import DSUpdater
from lib.datasources.utils import get_datasources


if __name__ == '__main__':
    with open(CONFIG_PATH, 'r', encoding='utf8') as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
    ds_updater = DSUpdater(config)

    def signal_handler(*_):
        ds_updater.cancel_update_thread()
        sys.exit()
    signal.signal(signal.SIGTERM, signal_handler)
    signal.signal(signal.SIGINT, signal_handler)

    ds_updater.start_update_thread()
    while True:
        time.sleep(30)
