#!/usr/bin/env python

import yaml
from flask import Flask, request
from lib.const import CONFIG_PATH
from lib.datasources.utils import get_datasources
from lib.qa_chain import QAChain

app = Flask(__name__)

@app.route('/salesforce', methods=['POST'])
def sf_query():
    with open(CONFIG_PATH, 'r', encoding='utf8') as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
    query = request.values['query']

    return QAChain(config, get_datasources(config)).ask(query)

if __name__ == '__main__':
    app.run(debug=True)
