#!/usr/bin/env venv/bin/python

import yaml
from flask import Flask, request, Response
from lib.const import CONFIG_PATH
from lib.chain import Chain

app = Flask(__name__)

@app.route('/ask_ai', methods=['POST'])
def ask_ai():
    with open(CONFIG_PATH, 'r', encoding='utf8') as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
    query = request.form.get('query')
    datasource = request.form.get('datasource')
    session = request.form.get('session')

    if query is None:
        return 'Query not specified', 400
    try:
        return Response(Chain(config).ask(query, ds_type=datasource, session=session), mimetype='text/plain')
    except ValueError:
        return 'Service unavailable', 400

if __name__ == '__main__':
    app.run(debug=True)
