CONFIG_PATH = 'config'
CONFIG_SETTING = 'setting'
CONFIG_LLM = 'llm'
CONFIG_PROMPT = 'prompt'
CONFIG_DATASOURCES = 'datasources'
CONFIG_QA_CHAIN_TYPE = 'qa_chain_type'
CONFIG_LLAMACPP = 'llamacpp'
CONFIG_OPENAI = 'openai'
CONFIG_HUGGINGFACE_PIPELINE = 'huggingface_pipeline'
CONFIG_MODEL_PATH = 'model_path'
CONFIG_OPENAI_API_KEY = 'openai_api_key'
CONFIG_MODEL_NAME = 'model_name'
CONFIG_SF = 'salesforce'
CONFIG_SF_USERNAME = 'username'
CONFIG_SF_PASSWORD = 'password'
CONFIG_SF_TOKEN = 'token'

META_DIR = 'metadata/'
