# Default values for remote_llm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  image: chengendu/remote_llm:latest

service:
  type: NodePort
  port: 30300

secret:
  token: <-huggingface-access-token->
