# Default values for support-ai.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  image: chengendu/support-ai:latest
  proxy: http://squid.internal:3128
  command: api-server
  port: 8080

service:
  type: NodePort
  port: 30300

configMap:
  llms:
  - name: default_llm
    type: remote
    url: test
  basic_model:
    llm: default_llm
  datasources:
  - type: salesforce
    authentication:
      username: ""
      password: ""
      token: ""
    llm: default_llm
    embeddings: default_llm
