apiVersion: v1
kind: Service
metadata:
  name: remote-llm
  namespace: chengen-du
spec:
  type: {{ .Values.service.type }}
  selector:
    app: remote-llm
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
